# Fama-MacBeth: 4 factor

## A

In [1]:
import pandas as pd
import numpy as np
import statsmodels.api as sm

In [2]:
factor = pd.read_excel('HW2.xlsx', sheet_name = 'SPX_DXY_MonthlyReturns')
factor.columns = ['Date', 'S&P 500 Index', 'US Dollar Index']
factor.index = factor.Date
factor.drop('Date', axis = 1, inplace = True)
factor.head()

S&P 500 Index  US Dollar Index
Date                                      
2001-07-31      -0.984416        -1.916799
2001-08-31      -6.260163        -3.208739
2001-09-30      -8.075231        -0.008817
2001-10-31       1.906875         1.278547
2001-11-30       7.670629         1.105694

In [3]:
df = pd.read_excel('HW2.xlsx', sheet_name = 'SP500Stocks',header = 1)
df.head()

NAME TICKER SECTOR  Market Cap ($ Mil)  \
0                  3m Co    MMM   INDU              110949   
1            Abbott Labs    ABT   HLTH              127036   
2             Abbvie Inc   ABBV   HLTH              138674   
3            Abiomed Inc   ABMD   HLTH               14640   
4  Accenture Plc Ireland    ACN   INFT               89887   

   2001-07-31 00:00:00  2001-08-31 00:00:00  2001-09-30 00:00:00  \
0            -1.945100            -6.446533            -5.475902   
1            12.112976            -7.258951             4.326061   
2                  NaN                  NaN                  NaN   
3           -19.423240            -1.315789            -6.826667   
4                  NaN            -0.401070           -14.429530   

   2001-10-31 00:00:00  2001-11-30 00:00:00  2001-12-31 00:00:00  ...  \
0             6.077282            10.339559             3.168009  ...   
1             2.599966             3.812730             1.363484  ...   
2                  NaN                  NaN                  NaN  ...   
3            24.441900           -12.741490           -16.605166  ...   
4            37.803922            28.628344            19.115044  ...   

   2018-03-31 00:00:00  2018-04-30 00:00:00  2018-05-31 00:00:00  \
0            -6.789357           -11.447915             2.149656   
1            -0.679629            -2.525512             5.848923   
2           -18.285435             3.070457             2.475368   
3             8.505481             3.422798            26.645622   
4            -4.664319            -0.615572             3.002638   

   2018-06-30 00:00:00  2018-07-31 00:00:00  2018-08-31 00:00:00  \
0            -0.258595             7.930319             0.006810   
1            -0.877646             7.939856             1.983455   
2            -6.357350             0.546199             4.065904   
3             7.322769           -13.328444            14.681409   
4             5.040437            -2.604036             6.113071   

   2018-09-30 00:00:00  2018-10-31 00:00:00  2018-11-30 00:00:00  \
0            -0.099670            -9.705245            10.030197   
1             9.754681            -5.645529             7.412211   
2            -1.458604           -16.817462            21.091854   
3            10.617837           -24.135631            -2.497069   
4             0.668382            -6.540393             4.377624   

   2018-12-31 00:00:00  
0            -8.358958  
1            -2.322711  
2            -2.206395  
3            -2.296501  
4           -14.290059  

[5 rows x 214 columns]

In [4]:
df0 = df.copy()
df0.index = df.NAME
df0.drop(['NAME','TICKER','SECTOR','Market Cap ($ Mil)'], axis = 1, inplace = True)
df1 = df0.T
df1.head()

NAME                     3m Co  Abbott Labs  Abbvie Inc  Abiomed Inc  \
2001-07-31 00:00:00  -1.945100    12.112976         NaN   -19.423240   
2001-08-31 00:00:00  -6.446533    -7.258951         NaN    -1.315789   
2001-09-30 00:00:00  -5.475902     4.326061         NaN    -6.826667   
2001-10-31 00:00:00   6.077282     2.599966         NaN    24.441900   
2001-11-30 00:00:00  10.339559     3.812730         NaN   -12.741490   

NAME                 Accenture Plc Ireland  Activision Blizzard Inc  \
2001-07-31 00:00:00                    NaN               -13.577718   
2001-08-31 00:00:00              -0.401070                 9.226306   
2001-09-30 00:00:00             -14.429530               -26.532794   
2001-10-31 00:00:00              37.803922                32.808711   
2001-11-30 00:00:00              28.628344                 3.113693   

NAME                 Adobe Sys Inc  Advance Auto Parts  Advanced Micro Devic  \
2001-07-31 00:00:00     -20.234087                 NaN            -36.816609   
2001-08-31 00:00:00     -10.349165                 NaN            -25.794085   
2001-09-30 00:00:00     -28.616782                 NaN            -39.852399   
2001-10-31 00:00:00      10.091781                 NaN             20.736196   
2001-11-30 00:00:00      21.515301                 NaN             37.804878   

NAME                  Aes Corp  ...  Willis Towers Watson Pu  \
2001-07-31 00:00:00 -11.033682  ...                -2.816904   
2001-08-31 00:00:00 -13.524804  ...                 9.043619   
2001-09-30 00:00:00 -61.292271  ...                24.348706   
2001-10-31 00:00:00   8.034321  ...                -0.427533   
2001-11-30 00:00:00  19.277978  ...                 1.674522   

NAME                 Wynn Resorts Ltd  Xcel Energy Inc  Xerox Corp  \
2001-07-31 00:00:00               NaN        -4.077114  -16.614480   
2001-08-31 00:00:00               NaN         1.707327   15.288163   
2001-09-30 00:00:00               NaN         4.106134  -15.760939   
2001-10-31 00:00:00               NaN         0.461629   -9.677419   
2001-11-30 00:00:00               NaN        -3.429815   20.000215   

NAME                 Xilinx Inc  Xylem Inc  Yum Brands Inc  Zimmer Hldgs Inc  \
2001-07-31 00:00:00   -3.006790        NaN        4.214608               NaN   
2001-08-31 00:00:00   -2.400000        NaN       -6.842003         -4.895105   
2001-09-30 00:00:00  -39.728484        NaN       -7.977550          2.022059   
2001-10-31 00:00:00   29.281768        NaN       28.990256         11.387387   
2001-11-30 00:00:00   18.704799        NaN       -6.206153          4.367519   

NAME                 Zions Bancorp  Zoetis Inc  
2001-07-31 00:00:00      -0.932129         NaN  
2001-08-31 00:00:00      -1.698511         NaN  
2001-09-30 00:00:00      -6.287271         NaN  
2001-10-31 00:00:00     -10.696854         NaN  
2001-11-30 00:00:00       1.164570         NaN  

[5 rows x 505 columns]

In [5]:
num_stocks = df1.shape[1]
num_stocks

505

In [6]:
num_months = df1.shape[0]
num_months

210

In [7]:
# for equity market factor & US Dollar factor

In [8]:
beta_mat = np.empty((num_stocks, 1 + len(factor.columns),))
beta_mat[:] = np.nan
beta_mat[:,0] = 1
beta_mat

array([[ 1., nan, nan],
       [ 1., nan, nan],
       [ 1., nan, nan],
       ...,
       [ 1., nan, nan],
       [ 1., nan, nan],
       [ 1., nan, nan]])

In [9]:
for i in range(0,num_stocks):
    y = df1.iloc[:,i]
    x = sm.add_constant(factor.to_numpy())
    model = sm.OLS(y,x,missing='drop').fit()
    beta_mat[i,1] = model.params[1]
    beta_mat[i,2] = model.params[2]
beta_mat       

array([[ 1.        ,  0.89727922,  0.13705929],
       [ 1.        ,  0.50103115, -0.09682999],
       [ 1.        ,  1.45009589, -0.55690148],
       ...,
       [ 1.        ,  0.72111827, -0.50389316],
       [ 1.        ,  1.13626781, -0.08487808],
       [ 1.        ,  0.97013304,  0.50179335]])

In [10]:
# for sector factor

In [11]:
df2 = df.iloc[:,:3]
df2.drop('TICKER',axis = 1,inplace = True)
df2.head()

NAME SECTOR
0                  3m Co   INDU
1            Abbott Labs   HLTH
2             Abbvie Inc   HLTH
3            Abiomed Inc   HLTH
4  Accenture Plc Ireland   INFT

In [12]:
sector_set = [np.nan]*len(df2.SECTOR.unique())
for i in range(len(df2.SECTOR.unique())):
    sector_set[i] = df2.SECTOR.unique()[i]
sector_set.remove('UTIL')
num_sector = len(sector_set)
l = np.zeros((num_stocks,num_sector))
df_sector = pd.DataFrame(l)
df_sector.columns = sector_set
df_sector.index = df2.NAME

In [13]:
for i in range(num_stocks):    
    for j in range(len(df_sector.columns)):        
        if df2['SECTOR'].iloc[i] != df_sector.columns[j]:
            continue
        if df2['SECTOR'].iloc[i] == df_sector.columns[j]:
            df_sector.iloc[i][j] = 1        
df_sector.head()          

INDU  HLTH  INFT  TCOM  DSCR  FINA  MATS  REAL  STPL  \
NAME                                                                          
3m Co                   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
Abbott Labs             0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
Abbvie Inc              0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
Abiomed Inc             0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
Accenture Plc Ireland   0.0   0.0   1.0   0.0   0.0   0.0   0.0   0.0   0.0   

                       ENER  
NAME                         
3m Co                   0.0  
Abbott Labs             0.0  
Abbvie Inc              0.0  
Abiomed Inc             0.0  
Accenture Plc Ireland   0.0

In [14]:
sector_exposure = df_sector.to_numpy()
sector_exposure

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [15]:
# for size factor

In [16]:
df3 = df.iloc[:,:4]
df3.drop('TICKER',axis = 1,inplace = True)
df3['log(Market Cap)'] = np.log(df3['Market Cap ($ Mil)'])
df3.head()

NAME SECTOR  Market Cap ($ Mil)  log(Market Cap)
0                  3m Co   INDU              110949        11.616826
1            Abbott Labs   HLTH              127036        11.752226
2             Abbvie Inc   HLTH              138674        11.839881
3            Abiomed Inc   HLTH               14640         9.591513
4  Accenture Plc Ireland   INFT               89887        11.406309

In [17]:
mean = df3.groupby('SECTOR')['log(Market Cap)'].mean()
mean

SECTOR
DSCR     9.668220
ENER     9.922564
FINA    10.069093
HLTH    10.382486
INDU     9.887828
INFT    10.225671
MATS     9.724490
REAL     9.682977
STPL    10.415517
TCOM    10.488791
UTIL     9.946875
Name: log(Market Cap), dtype: float64

In [18]:
std = df3.groupby('SECTOR')['log(Market Cap)'].std()
std

SECTOR
DSCR    1.016778
ENER    1.018311
FINA    1.008906
HLTH    1.014239
INDU    0.874319
INFT    1.136336
MATS    0.759010
REAL    0.629647
STPL    0.985399
TCOM    1.519808
UTIL    0.588647
Name: log(Market Cap), dtype: float64

In [19]:
size_exposure = np.empty((num_stocks,1))
for i in range(num_stocks):
    sector = df3['SECTOR'].iloc[i]
    size_exposure[i] = (df3['log(Market Cap)'].iloc[i] - mean[sector])/ std[sector]
size_exposure[:5]    

array([[ 1.97753756],
       [ 1.35051049],
       [ 1.43693526],
       [-0.77986894],
       [ 1.03898622]])

In [20]:
# combine factors and betas

In [21]:
factor_list = [factor.columns[0],factor.columns[1]]
for i in range(len(sector_set)):
    factor_list.append(sector_set[i])
factor_list.append('Market Cap')
factor_list

['S&P 500 Index',
 'US Dollar Index',
 'INDU',
 'HLTH',
 'INFT',
 'TCOM',
 'DSCR',
 'FINA',
 'MATS',
 'REAL',
 'STPL',
 'ENER',
 'Market Cap']

In [22]:
beta_mat = np.concatenate((beta_mat,sector_exposure,size_exposure), axis = 1)
df_beta_mat = pd.DataFrame(beta_mat)
l = ['Constant']
f = np.concatenate((l,factor_list), axis = 0)
df_beta_mat.columns = f
df_beta_mat.index = df3.NAME
df_beta_mat.head()

Constant  S&P 500 Index  US Dollar Index  INDU  HLTH  \
NAME                                                                          
3m Co                       1.0       0.897279         0.137059   1.0   0.0   
Abbott Labs                 1.0       0.501031        -0.096830   0.0   1.0   
Abbvie Inc                  1.0       1.450096        -0.556901   0.0   1.0   
Abiomed Inc                 1.0       1.263956         0.059849   0.0   1.0   
Accenture Plc Ireland       1.0       1.152855         0.193686   0.0   0.0   

                       INFT  TCOM  DSCR  FINA  MATS  REAL  STPL  ENER  \
NAME                                                                    
3m Co                   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
Abbott Labs             0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
Abbvie Inc              0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
Abiomed Inc             0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   
Accenture Plc Ireland   1.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   

                       Market Cap  
NAME                               
3m Co                    1.977538  
Abbott Labs              1.350510  
Abbvie Inc               1.436935  
Abiomed Inc             -0.779869  
Accenture Plc Ireland    1.038986

In [23]:
beta_mat

array([[ 1.        ,  0.89727922,  0.13705929, ...,  0.        ,
         0.        ,  1.97753756],
       [ 1.        ,  0.50103115, -0.09682999, ...,  0.        ,
         0.        ,  1.35051049],
       [ 1.        ,  1.45009589, -0.55690148, ...,  0.        ,
         0.        ,  1.43693526],
       ...,
       [ 1.        ,  0.72111827, -0.50389316, ...,  0.        ,
         0.        , -0.41687146],
       [ 1.        ,  1.13626781, -0.08487808, ...,  0.        ,
         0.        , -1.09363574],
       [ 1.        ,  0.97013304,  0.50179335, ...,  0.        ,
         0.        ,  0.23784225]])

In [24]:
# calculate factor returns at each time point

In [25]:
num_factor = len(factor_list)
num_factor

13

In [26]:
factor_ret = np.empty((num_factor,num_months))
factor_ret[:] = None
factor_ret

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])

In [27]:
df0.head()

2001-07-31  2001-08-31  2001-09-30  2001-10-31  \
NAME                                                                    
3m Co                   -1.945100   -6.446533   -5.475902    6.077282   
Abbott Labs             12.112976   -7.258951    4.326061    2.599966   
Abbvie Inc                    NaN         NaN         NaN         NaN   
Abiomed Inc            -19.423240   -1.315789   -6.826667   24.441900   
Accenture Plc Ireland         NaN   -0.401070  -14.429530   37.803922   

                       2001-11-30  2001-12-31  2002-01-31  2002-02-28  \
NAME                                                                    
3m Co                   10.339559    3.168009   -6.098369    6.805026   
Abbott Labs              3.812730    1.363484    3.886888   -1.993044   
Abbvie Inc                    NaN         NaN         NaN         NaN   
Abiomed Inc            -12.741490  -16.605166   -6.131479  -33.131313   
Accenture Plc Ireland   28.628344   19.115044   -4.234770    1.590380   

                       2002-03-31  2002-04-30  ...  2018-03-31  2018-04-30  \
NAME                                           ...                           
3m Co                   -2.475215    9.381248  ...   -6.789357  -11.447915   
Abbott Labs             -6.984970    3.014204  ...   -0.679629   -2.525512   
Abbvie Inc                    NaN         NaN  ...  -18.285435    3.070457   
Abiomed Inc             11.782477  -36.846847  ...    8.505481    3.422798   
Accenture Plc Ireland    1.947308  -19.700375  ...   -4.664319   -0.615572   

                       2018-05-31  2018-06-30  2018-07-31  2018-08-31  \
NAME                                                                    
3m Co                    2.149656   -0.258595    7.930319    0.006810   
Abbott Labs              5.848923   -0.877646    7.939856    1.983455   
Abbvie Inc               2.475368   -6.357350    0.546199    4.065904   
Abiomed Inc             26.645622    7.322769  -13.328444   14.681409   
Accenture Plc Ireland    3.002638    5.040437   -2.604036    6.113071   

                       2018-09-30  2018-10-31  2018-11-30  2018-12-31  
NAME                                                                   
3m Co                   -0.099670   -9.705245   10.030197   -8.358958  
Abbott Labs              9.754681   -5.645529    7.412211   -2.322711  
Abbvie Inc              -1.458604  -16.817462   21.091854   -2.206395  
Abiomed Inc             10.617837  -24.135631   -2.497069   -2.296501  
Accenture Plc Ireland    0.668382   -6.540393    4.377624  -14.290059  

[5 rows x 210 columns]

In [28]:
for t in range(num_months):
    y = df0.iloc[:,t]
    x = beta_mat
    model = sm.OLS(y,x,missing = 'drop').fit()
    factor_ret[:,t] = model.params[1:]
factor_ret = pd.DataFrame(factor_ret)    
factor_ret.columns = df0.columns
factor_ret.index = factor_list
factor_ret

2001-07-31  2001-08-31  2001-09-30  2001-10-31  2001-11-30  \
S&P 500 Index     -6.862857   -6.531107  -20.779600    9.164590   11.163984   
US Dollar Index    1.148899   -3.814941   -4.427043    5.534274    5.878303   
INDU               9.781195    0.346426    9.998076   -3.630006    2.105712   
HLTH               4.397612    0.190909    8.834765    2.879946    0.536815   
INFT               7.325754   -0.635126    8.745651    8.241545    3.268029   
TCOM               4.825124   -0.833424    5.572955    3.509324    0.349600   
DSCR              12.194093   -0.846280    6.145132    0.473640    4.318661   
FINA               7.337022   -0.366846   17.953474   -9.750611   -0.611098   
MATS               9.080813    2.162124   10.472454   -1.789567    4.865412   
REAL               3.769479    1.999704   12.708085   -6.354562    0.613596   
STPL               6.474854    0.586196    6.042393   -0.455695    2.977548   
ENER               5.315452   -3.381388    4.087406    7.848457   -8.522760   
Market Cap        -0.947414   -0.938464   -0.149607   -0.854275    0.910380   

                 2001-12-31  2002-01-31  2002-02-28  2002-03-31  2002-04-30  \
S&P 500 Index      1.215029   -4.323136   -5.533380    6.677938   -8.524798   
US Dollar Index   -0.502738   -1.612277   -3.514096   -0.359773   -4.333348   
INDU               0.565578    7.164433   10.661489  -10.552080    3.759445   
HLTH              -3.196261    0.527301    2.695108   -8.177159   -0.901076   
INFT              -1.688333    7.519178    0.528758   -6.466756   -2.971178   
TCOM              -2.472622    1.867889    9.126370   -9.292503    1.268775   
DSCR               3.370005   10.697396    8.667919  -11.619652    9.601583   
FINA              -1.179031    4.286246    7.722149   -9.511225    4.989156   
MATS              -2.591446    6.720628    9.879490   -7.862185    0.769461   
REAL              -2.717193    1.122977    3.366614   -6.494473    3.682304   
STPL              -3.028078    4.530565    6.709852   -9.232969    0.912770   
ENER               3.799435   -1.851951    9.980194   -2.622675    1.177210   
Market Cap        -0.802305   -0.177154   -0.705957   -0.449995   -0.616566   

                 ...  2018-03-31  2018-04-30  2018-05-31  2018-06-30  \
S&P 500 Index    ...   -1.541033   -2.245750    2.079768   -2.869671   
US Dollar Index  ...   -0.842876    0.077256    3.955822    1.263941   
INDU             ...   -4.432178   -4.305730    1.022698   -2.894414   
HLTH             ...   -5.581573   -1.403980    0.652143    0.176648   
INFT             ...   -4.275920   -0.903985    2.423637   -0.614386   
TCOM             ...   -8.487334   -0.950837    1.476050    9.945045   
DSCR             ...   -5.087975    0.796624    0.358355    1.071403   
FINA             ...   -5.830681   -0.698454   -2.097977   -2.526363   
MATS             ...   -6.761645   -0.783629    2.462243   -0.256819   
REAL             ...   -0.057924   -1.057510    2.456788    3.748026   
STPL             ...   -5.084995   -5.455916   -2.193325    2.916290   
ENER             ...   -0.680842    9.672145    3.682521    0.755149   
Market Cap       ...   -0.627375   -0.083263    0.615097   -0.458695   

                 2018-07-31  2018-08-31  2018-09-30  2018-10-31  2018-11-30  \
S&P 500 Index      1.789404   -1.263999   -0.475853   -7.030800    0.490195   
US Dollar Index    0.014721    1.749081   -1.058467    3.362589    1.699337   
INDU               4.583613    0.885673    2.033739   -8.910813    1.470327   
HLTH               3.401090    2.786344    3.402252   -8.664647    1.826115   
INFT              -1.094338    5.066053    1.080130   -6.393504   -2.400866   
TCOM              -5.979237    0.840789    3.112886   -0.741794   -4.752180   
DSCR              -1.414894    0.579908    1.160565   -4.720328   -1.780387   
FINA               0.872308   -0.221929   -1.441822   -2.727631   -0.899673   
MATS              -0.305439   -2.074810    0.625090   -5.299211    1.504166   
REAL

## B

In [29]:
for k in range(num_factor):  
    tmp_ret = factor_ret.iloc[k]
    est_rp = tmp_ret.mean()
    se_rp = tmp_ret.std()/np.sqrt(len(tmp_ret))
    tstat_rp = est_rp/se_rp
    print('---------------------\n',factor_list[k],'\n','Est Monthly RP = %.2f%%.\n' % est_rp, '\n', 
          'Std Error. = %.2f%%.\n' % se_rp, '\n', 'T-Stat = %.2f.\n' % tstat_rp) 

---------------------
 S&P 500 Index 
 Est Monthly RP = 0.22%.
 
 Std Error. = 0.36%.
 
 T-Stat = 0.61.

---------------------
 US Dollar Index 
 Est Monthly RP = 0.01%.
 
 Std Error. = 0.23%.
 
 T-Stat = 0.03.

---------------------
 INDU 
 Est Monthly RP = 0.21%.
 
 Std Error. = 0.30%.
 
 T-Stat = 0.69.

---------------------
 HLTH 
 Est Monthly RP = 0.41%.
 
 Std Error. = 0.29%.
 
 T-Stat = 1.44.

---------------------
 INFT 
 Est Monthly RP = 0.33%.
 
 Std Error. = 0.31%.
 
 T-Stat = 1.07.

---------------------
 TCOM 
 Est Monthly RP = 0.10%.
 
 Std Error. = 0.31%.
 
 T-Stat = 0.31.

---------------------
 DSCR 
 Est Monthly RP = 0.31%.
 
 Std Error. = 0.34%.
 
 T-Stat = 0.91.

---------------------
 FINA 
 Est Monthly RP = -0.16%.
 
 Std Error. = 0.35%.
 
 T-Stat = -0.46.

---------------------
 MATS 
 Est Monthly RP = 0.26%.
 
 Std Error. = 0.31%.
 
 T-Stat = 0.84.

---------------------
 REAL 
 Est Monthly RP = 0.36%.
 
 Std Error. = 0.31%.
 
 T-Stat = 1.16.

------------------

## C

## q1

In [33]:
w = np.dot(np.linalg.inv(np.dot(df_beta_mat.T,df_beta_mat)), df_beta_mat.T)

In [31]:
for i in range(1,num_factor+1):
    if w[i].sum() <= 0.0000000001:
        print('---------------------\n',factor_list[i-1],':\n', 'This factor portfolio is long-short neutral portfolio.\n')
    else:
        print('None')

---------------------
 S&P 500 Index :
 This factor portfolio is long-short neutral portfolio.

---------------------
 US Dollar Index :
 This factor portfolio is long-short neutral portfolio.

---------------------
 INDU :
 This factor portfolio is long-short neutral portfolio.

---------------------
 HLTH :
 This factor portfolio is long-short neutral portfolio.

---------------------
 INFT :
 This factor portfolio is long-short neutral portfolio.

---------------------
 TCOM :
 This factor portfolio is long-short neutral portfolio.

---------------------
 DSCR :
 This factor portfolio is long-short neutral portfolio.

---------------------
 FINA :
 This factor portfolio is long-short neutral portfolio.

---------------------
 MATS :
 This factor portfolio is long-short neutral portfolio.

---------------------
 REAL :
 This factor portfolio is long-short neutral portfolio.

---------------------
 STPL :
 This factor portfolio is long-short neutral portfolio.

---------------------
 

## q2

In [32]:
test_exposure = np.zeros((num_factor+1,num_factor+1))
for i in range(num_factor+1):
    for j in range(num_factor+1):
        test_exposure[i][j] = np.dot(w[i],df_beta_mat.iloc[:,j]).round()
test_exposure = pd.DataFrame(test_exposure)  
test_exposure

0    1    2    3    4    5    6    7    8    9    10   11   12   13
0   1.0  0.0 -0.0 -0.0 -0.0  0.0 -0.0  0.0 -0.0 -0.0 -0.0  0.0 -0.0  0.0
1   0.0  1.0 -0.0  0.0  0.0 -0.0  0.0  0.0  0.0 -0.0  0.0  0.0  0.0 -0.0
2  -0.0  0.0  1.0 -0.0  0.0  0.0  0.0  0.0 -0.0 -0.0  0.0  0.0 -0.0  0.0
3  -0.0 -0.0  0.0  1.0 -0.0 -0.0  0.0 -0.0  0.0  0.0 -0.0 -0.0 -0.0  0.0
4  -0.0 -0.0  0.0  0.0  1.0  0.0  0.0 -0.0  0.0  0.0 -0.0 -0.0 -0.0 -0.0
5  -0.0 -0.0  0.0  0.0 -0.0  1.0  0.0 -0.0  0.0  0.0 -0.0 -0.0  0.0  0.0
6  -0.0 -0.0  0.0  0.0 -0.0  0.0  1.0 -0.0 -0.0  0.0 -0.0 -0.0 -0.0 -0.0
7  -0.0 -0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0 -0.0 -0.0  0.0
8  -0.0 -0.0  0.0  0.0 -0.0  0.0  0.0 -0.0  1.0  0.0 -0.0 -0.0  0.0  0.0
9  -0.0 -0.0  0.0  0.0 -0.0 -0.0  0.0 -0.0 -0.0  1.0 -0.0 -0.0 -0.0  0.0
10 -0.0 -0.0  0.0  0.0  0.0 -0.0  0.0 -0.0 -0.0  0.0  1.0 -0.0 -0.0  0.0
11  0.0 -0.0  0.0  0.0 -0.0  0.0  0.0 -0.0  0.0  0.0 -0.0  1.0  0.0 -0.0
12 -0.0 -0.0  0.0  0.0 -0.0  0.0  0.0 -0.0 -0.0  0.0 -0.0 -0.0  1.0 -0.0
13  0.0  0.0  0.0  0.0  0.0  0.0  0.0 -0.0  0.0 -0.0 -0.0  0.0  0.0  1.0